Healthcheck bug fixes
OffchainLabs/arbitrum pull request #1025
Opened 2021-04-12 22:22 UTC by baburgess

2021-04-12 22:48 UTC, joshuacolvin0 approved these changes
LGTM

2021-04-13 02:03 UTC, hkalodner requested changes

2021-04-13 02:16 UTC, baburgess commented on packages/arb-node-core/staker/inboxReader.go
> +	if ir.healthChan != nil && from != nil {
There was a case were we hit a seg fault due to trying to use Set with a nil value in InboxReader. I added the checks just to make sure we avoided that if they were ever set to nil.

2021-04-14 21:52 UTC, joshuacolvin0 approved these changes
approving merge

2021-04-14 22:26 UTC, hkalodner approved these changes
LGTM

2021-04-14 22:26 UTC, merged