credit- back address param for registerTokenToL2 and setGateway
OffchainLabs/arbitrum pull request #1347
Opened 2021-07-02 23:12 UTC by DZGoldman

2021-07-07 18:01 UTC, fredlacs commented
Lets add a different function that exposes the credit-back address to avoid breaking changes

2021-07-07 18:04 UTC, fredlacs requested changes
I think we should add a different function that exposes the credit-back address to avoid breaking changes

2021-07-07 19:10 UTC, DZGoldman commented
I think we should keep only the recommended method in the ICustomToken.sol interface (thus this required updating the tests)

2021-07-09 12:32 UTC, fredlacs requested changes

2021-07-09 12:32 UTC, fredlacs commented on packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1CustomGateway.sol
> +            this.registerTokenToL2(
I think we should instead make `registerTokenToL2` public and call it that way.
`this. registerTokenToL2` makes an external evm call

2021-07-09 12:32 UTC, fredlacs commented on packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1CustomGateway.sol
>      ) external payable virtual returns (uint256) {
We could make this public instead of external to be called internally

2021-07-09 12:32 UTC, fredlacs commented on packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1GatewayRouter.sol
> +        this.setGateway(_gateway, _maxGas, _gasPriceBid, _maxSubmissionCost, msg.sender);
Should we instead `return setGateway(_gateway, _maxGas, _gasPriceBid, _maxSubmissionCost, msg.sender);`

2021-07-09 20:50 UTC, DZGoldman commented
updated @fredlacs

2021-07-12 12:27 UTC, fredlacs approved these changes
LGTM

2021-07-12 12:38 UTC, merged