Tooling rahul
OffchainLabs/arbitrum pull request #1355
Opened 2021-07-07 15:34 UTC by RahulMaganti47

added functionality to ensure arb-ts looks at l2 router instead of l1

2021-07-07 19:13 UTC, DZGoldman requested changes
Thanks @RahulMaganti47! Run this through the pre-commit hook, and also make sure it builds without errors (`yarn workspace arb-ts build`; it might just be the linting that's triggering the CI error)

2021-07-09 13:19 UTC, fredlacs commented on packages/arb-ts/src/lib/abi/L1ERC20Gateway.d.ts
> -  'counterpartGateway()'(overrides?: CallOverrides): Promise<string>
Accidental change?

2021-07-09 17:45 UTC, RahulMaganti47 commented on packages/arb-ts/src/lib/abi/L1ERC20Gateway.d.ts
> -  'counterpartGateway()'(overrides?: CallOverrides): Promise<string>
Yea my bad

2021-08-11 14:34 UTC, DZGoldman commented
merge conflict (also needs a pre-commit pass)

2022-07-01 16:08 UTC, closed without merging