Add a shared value cache for execution cursors
OffchainLabs/arbitrum pull request #1384
Opened 2021-07-15 14:40 UTC by PlasmaPower

2021-07-15 15:05 UTC, joshuacolvin0 approved these changes
LGTM

2021-07-15 21:24 UTC, hkalodner requested changes

2021-07-15 21:33 UTC, PlasmaPower commented on packages/arb-avm-cpp/data_storage/src/value/valuecache.cpp
> +    if (saving_cache_index == 0 && !caches.empty() && caches.back().empty() &&
Look at nextCache's implementation -- we're checking if the _previous_ cache is empty, as the current one is easily cleared. Perhaps a better check would be if all caches are empty.

2021-07-15 21:36 UTC, PlasmaPower commented on packages/arb-avm-cpp/data_storage/src/value/valuecache.cpp
> +    if (saving_cache_index == 0 && !caches.empty() && caches.back().empty() &&
I was only intending this function to run on an empty cache, though perhaps it shouldn't be limited as such.

2021-07-16 00:01 UTC, PlasmaPower commented on packages/arb-avm-cpp/data_storage/src/value/valuecache.cpp
> +    if (saving_cache_index == 0 && !caches.empty() && caches.back().empty() &&
I've changed this to not require an empty cache.

2021-07-16 19:55 UTC, hkalodner approved these changes
LGTM

2021-07-19 20:18 UTC, merged