refactor outbox/outbox entries to use single contract
OffchainLabs/arbitrum pull request #1385
Opened 2021-07-15 18:23 UTC by DZGoldman

2021-07-15 21:39 UTC, hkalodner requested changes

2021-07-15 21:39 UTC, hkalodner commented on packages/arb-bridge-eth/contracts/bridge/Outbox.sol
>          }
There shouldn't be any need to count number remaining or delete anything

2021-07-16 14:32 UTC, DZGoldman commented on packages/arb-bridge-eth/contracts/bridge/Outbox.sol
> +        return outboxEntries[outboxEntryIndex].root != bytes32(0);
Q: is the assumption of this existence check sound? (or should outboxEntries just include an `exists` bool)

2021-07-16 14:47 UTC, DZGoldman commented
TODO: add "outbox number" or "outbox version number" to each outbox

2021-07-16 20:15 UTC, hkalodner requested changes

2021-07-16 20:52 UTC, DZGoldman commented on packages/arb-bridge-eth/contracts/bridge/Outbox.sol
> +        return outboxEntries[outboxEntryIndex].root != bytes32(0);
it's really the equivalent usage on line 181 that matters (this one's just for client side convenience)

2021-07-16 20:52 UTC, DZGoldman commented on packages/arb-bridge-eth/contracts/bridge/Outbox.sol
>              uint256 numInBatch = data.toUint(33);
we use it in the OutboxEntryCreated event

2021-07-19 16:17 UTC, hkalodner approved these changes
LGTM

2021-07-19 17:57 UTC, fredlacs approved these changes
LGTM

2021-07-19 17:57 UTC, merged