Typechain cleanup
OffchainLabs/arbitrum pull request #1462
Opened 2021-08-08 16:06 UTC by hkalodner

2021-08-09 14:02 UTC, fredlacs requested changes
Looks good overall.
Left a couple small comments

2021-08-09 14:02 UTC, fredlacs commented on packages/arb-ts/src/lib/abi/hardhat.d.ts
> +/* Autogenerated file. Do not edit manually. */
Do we have a new contract named `hardhat` for this to get generated?

2021-08-09 14:21 UTC, fredlacs commented on packages/arb-ts/src/lib/abi/hardhat.d.ts
> +/* Autogenerated file. Do not edit manually. */
Ah seems like a new typechain feature
https://github.com/ethereum-ts/TypeChain/issues/370

2021-08-09 23:40 UTC, hkalodner commented on packages/arb-bridge-eth/tsconfig.json
> +  "include": ["./scripts", "./test", "./deploy", "./build/**/*.ts"],
The build path shows up in a ton of places so I think changing this would require a lot of changes that don't seem worth it

2021-08-09 23:40 UTC, hkalodner commented on .pre-commit-config.yaml
> +          - 'typescript@4.3.5'
Good call

2021-08-10 10:43 UTC, fredlacs approved these changes
LGTM

2021-08-10 12:58 UTC, merged