Validator improvements
OffchainLabs/arbitrum pull request #1787
Opened 2021-11-01 17:26 UTC by PlasmaPower

- [x] Fix inactive staker strategies
- [x] Withdraw funds from rollup contract
- [ ] Only create validator wallet when needed

2021-12-07 16:28 UTC, hkalodner requested changes

2021-12-07 16:28 UTC, hkalodner commented on packages/arb-node-core/staker/staker.go
> +			s.inactiveLastCheckedNode = nil
Probably clearer to lift this out of the if statement since it's the same in both clauses

2021-12-07 21:08 UTC, PlasmaPower commented on packages/arb-node-core/staker/staker.go
> +	}
I think we should think a bit more about how the authentication there would work. We'd either need to modify the rollup to only allow withdrawing to the validator itself, which seems a bit awkward, or have the validator wallet look at the function selector and filter based on that, which also seems a bit awkward.

2021-12-08 15:32 UTC, hkalodner submitted a review, later dismissed
LGTM

2022-01-24 20:37 UTC, hkalodner approved these changes
LGTM

2022-01-27 15:26 UTC, merged