arb-ts v2: new networks handling strategy (/ applied to retryable ticket creator)
OffchainLabs/arbitrum pull request #1907
Opened 2021-12-20 21:08 UTC by DZGoldman

2022-01-26 16:20 UTC, yahgwai approved these changes

2022-02-04 16:31 UTC, fredlacs requested changes

2022-02-04 16:31 UTC, fredlacs commented on packages/arb-ts/src/lib/L1ToL2Message/L1ToL2MessageCreator.ts
> +    return new L1ToL2MessageCreator(l1Signer, networksInfo)
also a `initFromL2ProviderOrChainID` would be a great function for NetworksInfo :)

2022-02-04 16:31 UTC, fredlacs commented on packages/arb-ts/src/lib/utils/networks.ts
>    customL1Network?: L1Network
is there a case in which a consumer wouldn't provide both custom networks?
```suggestion
  customL1Network: L1Network
  customL2Network: L2Network
```

2022-02-04 16:31 UTC, fredlacs commented on packages/arb-ts/src/lib/utils/networks.ts
> +      customNetworks && customNetworks.customL2Network
```suggestion
      customNetworks?.customL2Network
```

2022-02-08 18:46 UTC, closed without merging