Theoretically fix code reorgs
OffchainLabs/arbitrum pull request #1989
Opened 2022-01-20 05:02 UTC by PlasmaPower

Also simplifies `commitCodeToParent` (now called `commitCodeToRoot`)

2022-01-21 16:39 UTC, hkalodner requested changes

2022-01-21 17:06 UTC, PlasmaPower commented on packages/arb-avm-cpp/avm_values/include/avm_values/code.hpp
>          return loadCodeSegmentImpl(segment_num);
I've pushed up a commit which eliminates the double locking, though not the double getSegment. That said, the segment should be in the CPU's cache after its first retrieval, so I'd theorize that isn't as critical.

2022-01-21 20:21 UTC, hkalodner submitted a review, later dismissed
LGTM

2022-01-23 06:10 UTC, hkalodner approved these changes
LGTM

2022-01-23 06:18 UTC, merged