Cleanup elapsed time logging and improve database metadata reporting
OffchainLabs/arbitrum pull request #2028
Opened 2022-02-07 07:22 UTC by joshuacolvin0

Also add new arb-db tool to handle various database manipulations

2022-02-12 02:56 UTC, hkalodner requested changes

2022-03-04 02:07 UTC, joshuacolvin0 commented on packages/arb-avm-cpp/data_storage/include/data_storage/aggregator.hpp
> +    [[nodiscard]] uint64_t blockCountImpl(const ReadTransaction& tx) const;
no idea, reverted

2022-03-04 02:08 UTC, joshuacolvin0 commented on packages/arb-avm-cpp/data_storage/src/arbcore.cpp
> +    auto reorg_done = false;
:+1:

2022-03-04 02:39 UTC, joshuacolvin0 commented on packages/arb-avm-cpp/data_storage/src/arbcore.cpp
> +                } else {
:+1:

2022-03-04 03:21 UTC, hkalodner approved these changes
LGTM

2022-03-04 17:41 UTC, hkalodner approved these changes
LGTM

2022-03-04 17:58 UTC, merged