Make wallet creation explicit
OffchainLabs/arbitrum pull request #2138
Opened 2022-03-25 19:41 UTC by joshuacolvin0

If wallet is required and does not exist, user needs to add `--wallet.local.only-create-key` to the command line.  If wallet exists, command line must not have `--wallet.local.only-create-key`.

2022-03-28 16:16 UTC, PlasmaPower submitted a review, later dismissed
LGTM. We should remove the auth from watchtower validators too, but that's separate.

2022-03-29 02:03 UTC, hkalodner requested changes

2022-03-29 02:09 UTC, hkalodner approved these changes
LGTM

2022-03-29 02:09 UTC, joshuacolvin0 commented on packages/arb-node-core/cmdhelp/wallet.go
> +			}
:+1:

2022-03-29 02:27 UTC, merged