unify pages to "public chains" page; add Nova info
OffchainLabs/arbitrum pull request #2374
Opened 2022-07-21 15:20 UTC by DZGoldman

https://deploy-preview-52--hopeful-rosalind-235059.netlify.app/docs/public_chains
https://deploy-preview-52--hopeful-rosalind-235059.netlify.app/docs/useful_addresses

(from https://github.com/OffchainLabs/developer-website/pull/52)

2022-07-21 18:55 UTC, pearring commented on docs/Public_Chains.md
> +[Supported centralized exchanges](https://portal.arbitrum.one/#centralizedexchanges) allow you purchase (mainnet) Ether and withdraw it directly onto Arbitrum one.
```suggestion
[Supported centralized exchanges](https://portal.arbitrum.one/#centralizedexchanges) allow you to purchase (mainnet) Ether and withdraw it directly onto Arbitrum one.
```

2022-07-21 18:58 UTC, pearring commented on docs/Public_Chains.md
> +### What Next
```suggestion
### What's Next
```

2022-07-21 20:28 UTC, pearring commented on docs/Public_Chains.md
> +| Arbitrum Nova                            | 42170    | Mainnet | Ethereum      | Nitro AnyTrust     | [coming soon!]
I think we're ok to start using the new tld names:
Explorer: https://nova-explorer.arbitrum.io/
RPC URL: https://nova.arbitrum.io/rpc <-- we're already sending this to teams so it should be ok to share publicly?

2022-07-21 20:28 UTC, pearring commented on docs/Public_Chains.md
> +| Arbitrum Nova                            | 42170    | Mainnet | Ethereum      | Nitro AnyTrust     | [coming soon!]
for some reason it wouldn't let me issue a suggestion here

2022-07-21 20:31 UTC, pearring commented on docs/Public_Chains.md
> +To move your Ether and Tokens between Arbitrum and Ethereum chains at [bridge.arbitrum.io](https://bridge.arbitrum.io/).
```To move your Ether and Tokens between Arbitrum and Ethereum chains, visit[bridge.arbitrum.io](https://bridge.arbitrum.io/).```

2022-07-21 20:42 UTC, pearring requested changes
LGTM pending a few changes I added.

2022-07-25 14:56 UTC, DZGoldman commented
@pearring updated (preview build shows the latest)

2022-07-25 18:23 UTC, pearring approved these changes
LGTM

2022-07-25 18:23 UTC, merged