Deprecate bridge peripherals
OffchainLabs/arbitrum pull request #2518
Opened 2022-10-16 13:15 UTC by Jason-Wanxt

2022-10-16 16:30 UTC, gzeoneth submitted a review, later dismissed
LGTM

2022-10-19 14:09 UTC, fredlacs requested changes
lets do the same to `arb-bridge-eth`

2022-10-19 14:31 UTC, fionnachan commented on packages/arb-bridge-peripherals/README.md
> +This package has deprecated!
```suggestion
This package has been deprecated!
```

2022-10-20 12:33 UTC, fredlacs reviewed
lets add a note in `arb-bridge-eth`'s README

2022-10-24 05:42 UTC, gzeoneth submitted a review, later dismissed
one more change

2022-10-24 05:43 UTC, gzeoneth commented on packages/arb-bridge-eth/README.md
> +If you want to use what was once called `arb-bridge-eth`, look into the latest and greatest [`token-bridge-contracts`](https://github.com/OffchainLabs/token-bridge-contracts)!
should be nitro contracts instead, this is the rollup bridge

2022-10-24 11:59 UTC, fredlacs approved these changes
LGTM

2022-10-24 12:03 UTC, fredlacs approved these changes
LGTM

2022-10-24 15:19 UTC, merged