Sha256 precompile
OffchainLabs/arbitrum pull request #565
Opened 2020-09-11 16:13 UTC by hkalodner

- SHA256F added to cpp avm
- SHA256F added to ethbrige

TODO
- Add SHA256F to AVM spec
- Add test for SHA256 one step proof

2020-09-11 16:17 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6165536&bid=20135898)

2020-09-15 02:26 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6165536&bid=20135898)

2020-09-15 15:08 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6165536&bid=20135898)

2020-09-15 15:36 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6165536&bid=20135898)

2020-09-15 16:42 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6165536&bid=20135898)

2020-09-15 19:19 UTC, edfelten requested changes
Looks good, except for a few typos.

2020-09-15 19:19 UTC, edfelten commented on docs/AVM_Specification.md
> +The `sha256f` function is computer by the `sha256f` instruction. The function takes 3 Integers as input, and produces, and produces an Integer as output.
type: "computer" should be "computed"

2020-09-15 19:19 UTC, edfelten commented on docs/AVM_Specification.md
> +1. The 32 byte little-endian represention of the first item from the stack is interpretted as the digest and the 32 byte representations of the second and third items from the stack are concatenated
typo: "interpreted" should be "interpreted". (appears twice in this paragraph)

2020-09-15 19:19 UTC, edfelten commented on packages/arb-bridge-eth/contracts/libraries/Precompiles.sol
> +    // For subseuqent rounds, hashState is the output from the previous round
typo: "subseuqent" should be "subsequent"

2020-09-15 19:39 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6165536&bid=20135898)

2020-09-15 19:44 UTC, edfelten approved these changes

2020-09-15 19:52 UTC, merged