[WIP] Add opcodes for EC operations
OffchainLabs/arbitrum pull request #566
Opened 2020-09-17 22:32 UTC by hkalodner

2020-09-17 22:35 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Clones added
============
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-avm-cpp/tests/ecops.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6198618&bid=20219723)

2020-09-17 23:04 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Clones added
============
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-avm-cpp/tests/opcodes.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6198618&bid=20219723)

2020-09-17 23:29 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Clones added
============
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-avm-cpp/tests/ecops.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6198618&bid=20219723)

2020-09-18 03:11 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Clones added
============
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-avm-cpp/tests/opcodes.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6198618&bid=20219723)

2020-09-19 20:02 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Clones added
============
- packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp  2
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-avm-cpp/tests/ecops.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6198618&bid=20219723)

2020-09-21 16:05 UTC, edfelten requested changes
Looks good, just two requests.

2020-09-21 17:02 UTC, hkalodner commented on packages/arb-avm-cpp/avm/include/avm/machinestate/machineoperation.hpp
> +constexpr int max_ec_pairing_points = 100;
Fixed

2020-09-21 17:02 UTC, hkalodner commented on packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp
> +    uint64_t gas_cost = 0;
Fixed

2020-09-21 17:12 UTC, hkalodner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Clones added
============
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp  2
- packages/arb-avm-cpp/tests/opcodes.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6198618&bid=20219723)

2020-09-21 17:29 UTC, edfelten approved these changes
Looks good.

2020-09-21 17:32 UTC, merged