On chain inbox
OffchainLabs/arbitrum pull request #766
Opened 2021-02-17 04:57 UTC by hkalodner

Switch to storing all inbox messages on chain rather than just an accumulator

2021-02-17 05:19 UTC, joshuacolvin0 approved these changes
LGTM

2021-02-18 19:06 UTC, edfelten requested changes
Just one small issue in a comment.  Otherwise looks good.

2021-02-19 01:03 UTC, hkalodner commented on packages/arb-bridge-eth/contracts/rollup/Rollup.sol
>          // inboxMaxCount must be greater than beforeInboxCount since we can't have read past the end of the inbox
Updated comment

2021-02-19 16:14 UTC, edfelten approved these changes
Looks good.

2021-02-19 16:15 UTC, merged