Staker logic
OffchainLabs/arbitrum pull request #787
Opened 2021-02-28 22:38 UTC by PlasmaPower

2021-03-01 03:00 UTC, hkalodner requested changes

2021-03-01 03:00 UTC, hkalodner commented on packages/arb-node-core/staker/validator.go
> +	base, baseHash, err := v.validatorUtils.LatestStaked(ctx, address)
I think that as implemented, the watchtower strategy will always act as though it's on the latest confirmed. I think we need to instead find invalid nodes when they're initially posted

2021-03-01 03:12 UTC, PlasmaPower commented on packages/arb-node-core/ethbridge/rollupWatcher.go
> +		if parsedLog.ParentNodeHash != parentHash {
This was before I knew how log querying worked - I think it's fine, we need to trust our eth node anyways.

2021-03-03 06:11 UTC, hkalodner approved these changes
LGTM

2021-03-03 06:11 UTC, hkalodner commented on packages/arb-node-core/staker/staker_test.go
> +		} else if !faultyStakerAlive || !faultyStakerDead {
Schrödinger's staker?

2021-03-03 06:12 UTC, merged