Add deposit events
OffchainLabs/arbitrum pull request #924
Opened 2021-03-18 23:35 UTC by DZGoldman

2021-03-18 23:43 UTC, hkalodner requested changes

2021-03-18 23:43 UTC, hkalodner commented on packages/arb-bridge-eth/contracts/bridge/Inbox.sol
> +    event DepositEthRetryable(
Let's skip the Inbox.sol changes for now in the interest of finalizing for the testnet

2021-03-18 23:43 UTC, hkalodner commented on packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/EthERC20Bridge.sol
> +        address indexed destination,
Maybe also include sender?

2021-03-18 23:43 UTC, hkalodner commented on packages/arb-ts/src/lib/abi/ArbRetryableTx.d.ts
> -    'getSubmissionPrice(uint256)': FunctionFragment
This shouldn't have been deleted. You might be on an old ArbOS version

2021-03-19 00:42 UTC, DZGoldman commented
@hkalodner added the arb-ts updates to deposits to this branch  (https://github.com/OffchainLabs/arbitrum/pull/924/commits/4c7ae662e1020bb9e669e0705103e630a6ef4bd9)

2021-03-19 05:54 UTC, hkalodner approved these changes
LGTM

2021-03-19 06:30 UTC, merged